const actionTypes = {
    LOAD_USER_PLAYLISTS: 'LOAD_USER_PLAYLISTS',
    LOAD_USER_ALBUMS: 'LOAD_USER_ALBUMS',
    LOAD_USER_FOLLOW_ARTISTS: 'LOAD_USER_FOLLOW_ARTISTS',
    LOAD_USER_PROFILE: 'LOAD_USER_PROFILE',
    LOAD_ALBUM: 'LOAD_ALBUM',
    LOAD_PLAYLIST: 'LOAD_PLAYLIST',
    LOAD_ARTIST_ALBUMS: 'LOAD_ARTIST_ALBUMS',
    LOAD_BROWSE_GENRES: 'LOAD_BROWSE_GENRES',
    LOAD_BROWSE_FEATURED: 'LOAD_BROWSE_FEATURED',
    LOAD_BROWSE_NEW_RELEASES: 'LOAD_BROWSE_NEW_RELEASES',
    LOAD_SEARCH_ARTISTS: 'LOAD_SEARCH_ARTISTS',
    LOAD_SEARCH_ALBUMS: 'LOAD_SEARCH_ALBUMS',
    LOAD_SEARCH_PLAYLISTS: 'LOAD_SEARCH_PLAYLISTS',
    LOAD_SEARCH_TRACKS: 'LOAD_SEARCH_TRACKS',
    LOAD_VIEW_TRACKS: 'LOAD_VIEW_TRACKS',
    ADD_RECENT_SEARCH: 'ADD_RECENT_SEARCH',
    SET_SEARCH_TERM: 'SET_SEARCH_TERM',
    SET_SEARCH_TYPE: 'SET_SEARCH_TYPE',
    CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
    CHANGE_INPUT_READY: 'CHANGE_INPUT_READY'
};

export default actionTypes;