const actionTypes = {
    LOAD_USER_PLAYLISTS: 'LOAD_USER_PLAYLISTS',
    LOAD_USER_ALBUMS: 'LOAD_USER_ALBUMS',
    LOAD_USER_FOLLOW_ARTISTS: 'LOAD_USER_FOLLOW_ARTISTS',
    LOAD_USER_PROFILE: 'LOAD_USER_PROFILE',
    LOAD_ALBUM: 'LOAD_ALBUM',
    LOAD_PLAYLIST: 'LOAD_PLAYLIST',
    LOAD_ARTIST_ALBUMS: 'LOAD_ARTIST_ALBUMS',
    LOAD_BROWSE_GENRES: 'LOAD_BROWSE_GENRES',
    LOAD_BROWSE_FEATURED: 'LOAD_BROWSE_FEATURED',
    LOAD_BROWSE_NEW_RELEASES: 'LOAD_BROWSE_NEW_RELEASES',
    LOAD_VIEW_PLAYLISTS: 'LOAD_VIEW_PLAYLISTS'
};

export default actionTypes;