const actionTypes = {
    LOAD_PLAYLISTS: 'LOAD_PLAYLISTS',
    LOAD_ALBUMS: 'LOAD_ALBUMS',
    LOAD_FOLLOW_ARTISTS: 'LOAD_FOLLOW_ARTISTS',
    LOAD_ALBUM: 'LOAD_ALBUM',
    LOAD_PLAYLIST: 'LOAD_PLAYLIST',
    LOAD_ARTIST: 'LOAD_ARTIST'
}

export default actionTypes;